version: '3.8'

services:
  app:
    build: .
    container_name: query-generator-app
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: query-generator-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    secrets:
      - ssl_cert
      - ssl_key
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

secrets:
  ssl_cert:
    file: ./hapticlabs.uk.pem
  ssl_key:
    file: ./hapticlabs.uk.key
